#pragma once

extern void TLTYPE(VECTOR *, int);
extern void TLTYPECOMP(int, int, VECTOR *);
extern void TLENDTYPE(int);
extern void TLSEG(int32, int32, int32, int32, int32);
extern void TLLOAD(int, int);
extern void TLCODEAREA(int);
extern void TLDATAAREA(int);
extern void TLSPACE(int);
extern void TLSDECL(VECTOR *, int, int);
extern void TLVDECL(VECTOR *, uint32, int, int, int, int);
extern void TLMAKE(int, int, int);
extern void TLSELECTVAR(void);
extern void TLSELECTFIELD(int, int, int);
extern void TLASS(int, int);
extern void TLASSVALUE(int, int);
extern void TLASSEND(void);
extern void TLCLIT16(int, int16);
extern void TLCLIT32(int, int32);
extern void TLCLIT64(int, t_uint64);
extern void TLCNULL(int);
extern void TLCLITS(int, VECTOR *);
extern void TLCLIT128(int, double);
extern void TLLIT(VECTOR *, int);
extern void TLPROCSPEC(VECTOR *, int);
extern void TLPROCPARAM(int, int);
extern void TLPROCRESULT(int);
extern void TLPROC(int);
extern void TLPROCKIND(int);
extern void TLENDPROC(void);
extern void TLBLOCK(void);
extern void TLENDBLOCK(void);
extern void TLENTRY(int);
extern void TLLABELSPEC(VECTOR *, int);
extern void TLLABEL(int);
extern void TLPL(int, int);
extern void TLDTYPE(int, int);
extern void TLINSERT(int);
extern void TLCHECK(int);
extern void TLREG(int);
extern void TLLINE(int32);
extern void TLPRINT(int);
extern void TL(int, char *, int);
extern void TLEND(void);
extern void TLMODULE(void);
extern void TLENDMODULE(int);
extern void TLMODE(int, int);
